export const ERROR_CODES = {
  // Auth
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_SESSION_EXPIRED: "AUTH_SESSION_EXPIRED",
  AUTH_EMAIL_NOT_VERIFIED: "AUTH_EMAIL_NOT_VERIFIED",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_ACCOUNT_SUSPENDED: "AUTH_ACCOUNT_SUSPENDED",
  AUTH_ACCOUNT_DEACTIVATED: "AUTH_ACCOUNT_DEACTIVATED",

  // Organization
  ORGANIZATION_NOT_FOUND: "ORGANIZATION_NOT_FOUND",
  ORGANIZATION_SLUG_RESERVED: "ORGANIZATION_SLUG_RESERVED",
  ORGANIZATION_SLUG_TAKEN: "ORGANIZATION_SLUG_TAKEN",
  ORGANIZATION_SLUG_INVALID: "ORGANIZATION_SLUG_INVALID",
  ORGANIZATION_LAST_OWNER: "ORGANIZATION_LAST_OWNER",
  ORGANIZATION_SUSPENDED: "ORGANIZATION_SUSPENDED",

  // Branch
  BRANCH_NOT_FOUND: "BRANCH_NOT_FOUND",
  BRANCH_CODE_ALREADY_EXISTS: "BRANCH_CODE_ALREADY_EXISTS",
  BRANCH_ARCHIVED: "BRANCH_ARCHIVED",

  // Academic Session
  ACADEMIC_SESSION_NOT_FOUND: "ACADEMIC_SESSION_NOT_FOUND",
  ACADEMIC_SESSION_CODE_ALREADY_EXISTS: "ACADEMIC_SESSION_CODE_ALREADY_EXISTS",
  ACADEMIC_SESSION_INVALID_DATE_RANGE: "ACADEMIC_SESSION_INVALID_DATE_RANGE",

  // Membership
  MEMBERSHIP_NOT_FOUND: "MEMBERSHIP_NOT_FOUND",
  MEMBERSHIP_ALREADY_EXISTS: "MEMBERSHIP_ALREADY_EXISTS",
  MEMBERSHIP_SUSPENDED: "MEMBERSHIP_SUSPENDED",

  // Role
  ROLE_NOT_FOUND: "ROLE_NOT_FOUND",
  ROLE_SCOPE_MISMATCH: "ROLE_SCOPE_MISMATCH",
  ROLE_SYSTEM_PROTECTED: "ROLE_SYSTEM_PROTECTED",
  ROLE_ASSIGNMENT_DUPLICATE: "ROLE_ASSIGNMENT_DUPLICATE",
  ROLE_ASSIGNMENT_NOT_FOUND: "ROLE_ASSIGNMENT_NOT_FOUND",

  // Permission
  PERMISSION_DENIED: "PERMISSION_DENIED",
  PERMISSION_NOT_FOUND: "PERMISSION_NOT_FOUND",

  // Invitation
  INVITATION_NOT_FOUND: "INVITATION_NOT_FOUND",
  INVITATION_EXPIRED: "INVITATION_EXPIRED",
  INVITATION_REVOKED: "INVITATION_REVOKED",
  INVITATION_ALREADY_ACCEPTED: "INVITATION_ALREADY_ACCEPTED",
  INVITATION_EMAIL_ALREADY_MEMBER: "INVITATION_EMAIL_ALREADY_MEMBER",
  INVITATION_DUPLICATE_PENDING: "INVITATION_DUPLICATE_PENDING",

  // Assessment
  ASSESSMENT_NOT_FOUND: "ASSESSMENT_NOT_FOUND",
  ASSESSMENT_INVALID_STATE: "ASSESSMENT_INVALID_STATE",
  ASSESSMENT_INVALID_MARKS: "ASSESSMENT_INVALID_MARKS",
  ASSESSMENT_CONTEXT_MISMATCH: "ASSESSMENT_CONTEXT_MISMATCH",
  ASSESSMENT_DATE_OUTSIDE_ACADEMIC_CONTEXT:
    "ASSESSMENT_DATE_OUTSIDE_ACADEMIC_CONTEXT",
  ASSESSMENT_RESULTS_INCOMPLETE: "ASSESSMENT_RESULTS_INCOMPLETE",
  ASSESSMENT_RESULTS_PUBLISHED: "ASSESSMENT_RESULTS_PUBLISHED",
  ASSESSMENT_RESULT_INVALID: "ASSESSMENT_RESULT_INVALID",
  ASSESSMENT_ENROLLMENT_NOT_ELIGIBLE: "ASSESSMENT_ENROLLMENT_NOT_ELIGIBLE",
  EDUCATION_CROSS_TENANT_REFERENCE: "EDUCATION_CROSS_TENANT_REFERENCE",

  // General
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  RATE_LIMITED: "RATE_LIMITED",
} as const;
